version: "2.2"
services:

  nginx:
    image: nginx:1.13.7-alpine
    container_name: metricbeat-nginx
    volumes:
      - ./config/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx

networks:
  nginx:
    external:
      name: metricbeat


