version: "2.2"
services:

  rabbitmq:
    image: bijukunjummen/rabbitmq-server:3.6.5
    container_name: metricbeat-rabbitmq
    environment:
      TCP_PORTS: "5672,15672"
    ports:
      - "127.0.0.1:1234:15672"
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external:
      name: metricbeat


